import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="nav">
          <Link className="nav__item" href={"/"}>
            Dashboard
          </Link>
          <Link className="nav__item" href={"/upload"}>
            Upload csv
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
